
CREATE TABLE board (
    id           INTEGER AUTO_INCREMENT PRIMARY KEY,
    title        VARCHAR(100) NOT NULL,
    description  VARCHAR(100) NOT NULL,
    status       INTEGER NOT NULL,
    created_dt   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_dt  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE status (
    id    INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL
);

INSERT INTO status(title) VALUES('PUBLIC', 'PRIVATE');